model: pcmci
lag: 2 
dream3_size: 100

trainer:
  _target_: src.baselines.PCMCITrainer.PCMCITrainer
  _partial_: true

  ci_test: ParCorr
  single_graph: true
  pcmci_plus: true
  pc_alpha: 0.01

  group_by_graph: false