
# graph settings
num_timesteps: 100
lag: 2
history_dep_noise : true
burnin_length: 100
noise_level: 0.5
function_type: mlp # options: mlp, spline, linear, spline_product, conditional_spline, mlp_noise, inverse_noise_spline
noise_function_type: spline_product # options: same as function_type
base_noise_type: gaussian # options: gaussian, uniform
num_samples: 1000

disable_inst: false # whether to exclude instantaneous edges
inst_graph_type: ER # options: SF, ER
lag_graph_type: ER # options: SF, ER
save_dir: "data/synthetic"

random_seed: 
- 0
# - 1
# - 2
# - 3
# - 4
# - 5

num_nodes:
- 5
- 10
- 20
- 40

num_graphs:
- 1
- 5
- 10
- 20
# - 40
# - 60
# - 80
# -