name: Runs pytests and generates coverage report

on: [pull_request]

jobs:
  
  # This workflow contains a single job called "test"
  run_pytest:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install flake8 pytest pytest-cov

      - name: Build coverage file
        run: |
          pytest --cache-clear --cov=src tests/ > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
